apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-api-deployment
  annotations:
    kubernetes.io/change-cause: "Initial setup"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: messenger-api
  template:
    metadata:
      name: messengerApp
      labels:
        env: prod
        app: messenger-api
        app.kubernetes.io/name: messenger-api
    spec:
      containers:
        - name: messenger-api
          image: aarnass75/messenger-api:latest
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

---

apiVersion: v1
kind: Service
metadata:
  name: my-load-balancer-service
spec:
  selector:
    app.kubernetes.io/name: messenger-api
  ports:
    - name: messenger-api-port
      protocol: TCP
      port: 7070
      targetPort: 80
  type: LoadBalancer
    